public with sharing class NewGeneratedAccounts {
    
    public string userId;
    public List<new_T> new_T;
    
    public class new_T
    {
        public Attributes attributes;
        public boolean IsDeleted;
        public string CleanStatus;
        public  string OwnerId;
        public  string Name;

        public string AccountNumber;      
        
			        
      
    }
    
    
    
      public class Attributes{
            
            public string Type_x;
            
        }
        
    public class old
    {
               
        
      
    }
}
